### PR TITLE
types to interfaces

### PR DESCRIPTION
**Pull request by kadiryazici**
Can you check this before pushing?

### CODE REVIEW

**Comment by frandiox** [comment]
@kadiryazici Thanks! Does this allow you to override types directly from your app?

**Comment by kadiryazici** [comment]
> @kadiryazici Thanks! Does this allow you to override types directly from your app?

I don't know, maybe.

**Comment by kadiryazici** [comment]
Yes it does. I transformer `types` to `interfaces` in my library `vite-ssr-middleware`. Now user is able to define their own `CustomProperties` type.
https://github.com/kadiryazici/vite-ssr-middleware#typed-custom-properties

**Comment by frandiox** [comment]
@kadiryazici Thanks! I will do this for React types as well.

**Pull request merged**
